name: smart_food_app
description: "A new Flutter project for food nutrition scanning and analysis."
publish_to: "none" # Remove this line if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: any
  http: any
  camera: ^0.10.5+9
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.4
  fl_chart: ^0.66.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  speech_to_text: ^6.6.0
  intl: ^0.19.0
  google_ml_kit: ^0.16.2
  path_provider: ^2.1.5
  path: ^1.8.3
  simple_web_camera: ^1.0.11
  firebase_core: ^3.15.1
  firebase_database: ^11.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/apple logo.jpg
